version: '3.8'

services:
  web:
    container_name: node-web
    image: app
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
        target: base
    command:
      - bash
      - -c
      - |
        npm install --dev
        npm run dev
    tty: true
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    networks:
      - servicenetwork
    depends_on:
      - db

  db:
    container_name: mongo-db
    image: mongo
    volumes:
      - mongodb_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - servicenetwork

networks:
  servicenetwork:
    driver: bridge

volumes:
  mongodb_data:
    driver: local