# Use root/example as user/password credentials
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  app:
    image: app
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
        target: base
    ports:
        - "${PORT}:${PORT}"
