# Use root/example as user/password credentials
services:
  web:
    container_name: node-web
    image: app
    restart: always
    build:
        context: .
        dockerfile: Dockerfile
        target: base
    command:
      - bash
      - -c
      - |
        npm run dev
    tty: true
    volumes:
      - .:/app
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - db
  db:
    container_name: mongo-db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    #no output
    logging:
      driver: "none"
    ports:
      - "${DB_PORT}:${DB_PORT}"



